### ISSUE TITLE
Could not find :tpdirect: when running the app

### ISSUE THREAD

**Issue by Ibrahimsyah** [VeryBuy/react-native-tappay#20]
Hi,
I was trying to implement the tappay on my react native project. But when I run it, it throws an error listed below
```
   > Could not find :tpdirect:.
     Required by:
         project :app > project :react-native-tappay
```
My react native version is 0.61.2
I have tried to manual linking, reinstall the plugin, and run ```./gradlew clean``` but the problem still exists

**Comment by blackbing** [comment]
It seems like you don't get the android SDK. What platform do you use? Mac or Windows?

**Comment by Ibrahimsyah** [comment]
> It seems like you don't get the android SDK. What platform do you use? Mac or Windows?

I use linux for developing it. Before installing the plugin, my app was fine. Is it related to android SDK?

**Comment by blackbing** [comment]
can you provide package.json and android/app/build.gradle?

**Comment by Ibrahimsyah** [comment]
> can you provide package.json and android/app/build.gradle?
Here is my zipped package.json and build.gradle
[tappaydemo.zip](https://github.com/VeryBuy/react-native-tappay/files/7703028/tappaydemo.zip)

FYI that is a fresh react native project, I've tried this example https://github.com/VeryBuy/react-native-tappay/tree/master/example but the error is still occured

**Comment by Dylan0916** [comment]
@Ibrahimsyah sorry for the trouble, we'll fix it as soon as possible

**Comment by Ibrahimsyah** [comment]
Many thanks!

**Comment by Dylan0916** [comment]
@blackbing Hi, we have updated the code in the example, plz try again. 😆

**Comment by Dylan0916** [comment]
@Ibrahimsyah Hi, we have updated the code in the example, plz try again. 😆

**Comment by Ibrahimsyah** [comment]
It works and runs perfectly! many thanks!. But I think it would be better if we can fix the issues without editing android/ dir. I don't know whether it is possible or not, but that will make the package less-coupled with the android and user don't need to edit their gradle manually after installation 😇

**Comment by Dylan0916** [comment]
Thanks for the suggestion, we'll look into how to do it.
