### ISSUE TITLE
Could not find :tpdirect: while running react-native run-android

### ISSUE THREAD

**Issue by matteo1222** [VeryBuy/react-native-tappay#36]
I am trying to use react-native-tappay and running the command `npx react-native run-android` to test on a physical device. The process failed with the following error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :tpdirect:.
     Required by:
         project :app > project :react-native-tappay

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
What would be the next step the solve the issue? I am using React Native 0.66.0 and react-native-tappay 1.3.2. Thank you very much for your help.

**Comment by blackbing** [comment]
Hi @matteo1222 add these lines in your project https://github.com/VeryBuy/react-native-tappay/blob/master/example/android/build.gradle#L34-L36

**Comment by matteo1222** [comment]
It worked. Thank you so much!

**Comment by blackbing** [comment]
@Dylan0916 could you please add this step to README?

**Comment by Dylan0916** [comment]
Sure~
