### ISSUE TITLE
LinePay 

### ISSUE THREAD

**Issue by wiwi1234** [VeryBuy/react-native-tappay#39]
目前可以透過useTapPay, isLoadedSuccess 是true. 
<img width="892" alt="截圖 2022-05-04 下午3 32 02" src="https://user-images.githubusercontent.com/23716793/166640203-03957929-ed82-4279-a79f-42bb35127605.png">
但是我實際拿一台有linepay的手機測試卻一直是false.
<img width="892" alt="截圖 2022-05-04 下午3 32 58" src="https://user-images.githubusercontent.com/23716793/166640578-8ab00b09-28b6-4639-b369-f8624318a4ab.png">
想請問我是有什麼設定沒有設定到嗎 ～謝謝
<img width="892" alt="截圖 2022-05-04 下午3 35 26" src="https://user-images.githubusercontent.com/23716793/166640710-aa4aa8f7-b649-4b69-9d99-4166f03beb47.png">

**Comment by blackbing** [comment]
有確認 tappay 後台已開啟 LinePay 了嗎？

**Comment by blackbing** [comment]
另外 LinePay 的設定需要 follow 文件：
https://github.com/TapPay/tappay-ios-example#5-setup-custom-url-scheme
step5 - step6

**Comment by blackbing** [comment]
Add LinePay example, please checkout pr:
https://github.com/VeryBuy/react-native-tappay/pull/40
