### ISSUE TITLE
Line Pay Transaction Fail

### ISSUE THREAD

**Issue by wiwi1234** [VeryBuy/react-native-tappay#56]
Hi IT大大,
想請問收到的 payment_url 要怎麼處理呢?
嘗試使用 handleLinePayURL 但是 return error : Line Pay Transaction Fail 
是否為LinePay Url 格式不對呢?
這是我收到的payment_url 格式 : line://pay/payment/dDR5OFNMaGw1RVhJOVdFWU1COXJHRmI2VlpLTURyWWJGNisrSmxyZlhlOEdXMmhDOXR6ZlNORkhVUmpSdmlSZw

Code: 
<img width="856" alt="截圖 2022-12-30 上午10 51 15" src="https://user-images.githubusercontent.com/23716793/210029743-5b839661-ec53-4c98-b49e-2f7f91bfbf3d.png">

Frontend return url :
![S__30507031](https://user-images.githubusercontent.com/23716793/210029746-d38da45b-2b59-4660-aeb6-2c7cc8c80411.jpg)

任何幫忙都很感謝 ~

**Comment by blackbing** [comment]
請參考這個 pr 確認是否有正確設定 linePay 的綁定，如果還有問題就需要跟 Tappay 確認了

**Comment by wiwi1234** [comment]
了解 ~ 謝謝回覆

**Comment by blackbing** [comment]
PR link https://github.com/VeryBuy/react-native-tappay/pull/40
